package com.test.restservices.helloworld;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloWorldController {
	@RequestMapping(method = RequestMethod.GET, path= "/test")
	public String helloworld(){
		return "This is a Sample string generated by Nevin";
	}
}
